const express = require('express');
const router = express.Router();
const authRoutes = require('./authRoutes');
const approvalRoutes = require('./approvalRoutes');
const farmRoutes = require('./farmRoutes');
const cropRoutes = require('./cropRoutes');
const advisoryRoutes = require('./advisoryRoutes');
const walletRoutes = require('./walletRoutes');
const suggestionsRoutes = require('./suggestionsRoutes');
const farmGuidelineRoutes = require('./farmGuidelineRoutes');
const chatbotRoutes = require('./chatbotRoutes');
const weatherRoutes = require('./weatherRoutes');
const diseaseDetectionRoutes = require('./diseaseDetectionRoutes');
const adminAnalyticsRoutes = require('./adminAnalyticsRoutes');
const productRoutes = require('./productRoutes');
const marketRoutes = require('./marketRoutes');
const expertRoutes = require('./expertRoutes');
const forumRoutes = require('./forumRoutes');
const adminRoutes = require('./adminRoutes');
const cartRoutes = require('./cartRoutes');
const checkoutRoutes = require('./checkoutRoutes');
const adminEcommerceRoutes = require('./adminEcommerceRoutes');
const consultationRoutes = require('./consultationRoutes');
const voiceRoutes = require('./voiceRoutes');

router.use('/auth', authRoutes);
router.use('/approvals', approvalRoutes);
router.use('/farms', farmRoutes);
router.use('/crops', cropRoutes);
router.use('/advisories', advisoryRoutes);
router.use('/wallet', walletRoutes);
router.use('/suggestions', suggestionsRoutes);
router.use('/guidelines', farmGuidelineRoutes);
router.use('/chatbot', chatbotRoutes);
router.use('/weather', weatherRoutes);
router.use('/disease-detection', diseaseDetectionRoutes);
router.use('/admin/analytics', adminAnalyticsRoutes);
router.use('/products', productRoutes);
router.use('/markets', marketRoutes);
router.use('/experts', expertRoutes);
router.use('/forums', forumRoutes);
router.use('/admin', adminRoutes);
router.use('/cart', cartRoutes);
router.use('/checkout', checkoutRoutes);
router.use('/orders', checkoutRoutes); // Orders use checkout controller
router.use('/admin/ecommerce', adminEcommerceRoutes);
router.use('/consultations', consultationRoutes);
router.use('/voice', voiceRoutes);
module.exports = router;